# Generated by Django 2.0.5 on 2018-05-28 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('typ', models.CharField(choices=[('abs_end', 'Abstract Submission Deadline'), ('art_end', 'Article Submission Deadline'), ('abs_beg', 'Abstract Submission starts'), ('accept', 'Acceptation notice'), ('reg_end', 'Registration Deadline'), ('erg_end', 'Early Registration Deadline'), ('other', 'Other')], max_length=7)),
                ('description', models.CharField(help_text='Only if type is "Other"', max_length=100, null=True)),
                ('extended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=15, null=True)),
                ('short_description', models.CharField(max_length=40, null=True)),
                ('published', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('gps_lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('gps_lon', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('item', models.FileField(upload_to='uploads/files/%Y%m%d/')),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=160)),
                ('entity', models.CharField(help_text='Institution (univ., agency or company) that offers the job', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('published', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('gps_lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('gps_lon', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('files', models.ManyToManyField(to='website_core.FileItem')),
            ],
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='uploads/news/%Y%m%d/')),
                ('files', models.ManyToManyField(to='website_core.FileItem')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='files',
            field=models.ManyToManyField(to='website_core.FileItem'),
        ),
        migrations.AddField(
            model_name='dateitem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_core.Event'),
        ),
    ]
