# Generated by Django 2.0.5 on 2018-05-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_core', '0002_auto_20180528_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dateitem',
            old_name='typ',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='dateitem',
            name='description',
            field=models.CharField(blank=True, help_text='Only if type is "Other"', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='files',
            field=models.ManyToManyField(blank=True, to='website_core.FileItem'),
        ),
        migrations.AlterField(
            model_name='event',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='gps_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='files',
            field=models.ManyToManyField(blank=True, to='website_core.FileItem'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='gps_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='files',
            field=models.ManyToManyField(blank=True, to='website_core.FileItem'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/news/%Y%m%d/'),
        ),
    ]
