# Generated by Django 2.0.5 on 2018-05-28 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('website_core', '0003_auto_20180528_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='files',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='files',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='files',
        ),
        migrations.AddField(
            model_name='fileitem',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileitem',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
