# Generated by Django 2.0.5 on 2018-05-28 14:27

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('website_core', '0004_auto_20180528_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelWithFiles',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
