# Generated by Django 2.0.5 on 2018-05-28 14:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_core', '0005_auto_20180528_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='thi', editable=True, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
