# Generated by Django 2.0.5 on 2018-06-03 16:13

import autoslug.fields
from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('website_core', '0006_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
