# Generated by Django 2.0.5 on 2018-06-03 16:35

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_core', '0007_auto_20180603_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='a', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
