# Generated by Django 2.0.5 on 2018-06-03 16:38

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_core', '0008_newsitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='a', editable=False, populate_from='__compound_position', unique=True),
            preserve_default=False,
        ),
    ]
