# Generated by Django 2.0.5 on 2018-06-03 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_core', '0010_auto_20180603_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateitem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='website_core.Event'),
        ),
    ]
