# Generated by Django 2.0.5 on 2018-06-03 22:16

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('website_core', '0013_auto_20180603_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewletterIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('free_text', markdownx.models.MarkdownxField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitute (for mapping purposes)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='gps_lon',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude (for mapping purposes)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Where does the event happens', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=True, help_text='Should the event be displayed publicly?'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitute (for mapping purposes)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='gps_lon',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude (for mapping purposes)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='published',
            field=models.BooleanField(default=True, help_text='Should the event be displayed publicly?'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Image to be use as title image', null=True, upload_to='uploads/news/%Y%m%d/'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='published',
            field=models.BooleanField(default=True, help_text='Should the event be displayed publicly?'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(help_text='Keep it short and punchy!', max_length=160),
        ),
        migrations.AddField(
            model_name='newletterissue',
            name='events',
            field=models.ManyToManyField(to='website_core.Event'),
        ),
        migrations.AddField(
            model_name='newletterissue',
            name='jobs',
            field=models.ManyToManyField(to='website_core.JobOffer'),
        ),
        migrations.AddField(
            model_name='newletterissue',
            name='news',
            field=models.ManyToManyField(to='website_core.NewsItem'),
        ),
    ]
