# Generated by Django 2.0.5 on 2018-06-03 22:21

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('website_core', '0014_auto_20180603_2216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewletterIssue',
            new_name='NewsletterIssue',
        ),
    ]
