# Generated by Django 2.0.5 on 2018-06-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_core', '0015_auto_20180603_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterissue',
            name='events',
        ),
        migrations.AddField(
            model_name='newsletterissue',
            name='dates',
            field=models.ManyToManyField(to='website_core.DateItem'),
        ),
    ]
