# Generated by Django 2.0.5 on 2018-07-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_core', '0018_auto_20180711_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='map_object',
            field=models.TextField(blank=True, null=True),
        ),
    ]
