# Generated by Django 2.0.5 on 2019-01-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_core', '0020_indexsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexsection',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
