# Generated by Django 2.0.5 on 2019-01-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_core', '0021_indexsection_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='map_object',
            new_name='map_text',
        ),
        migrations.AddField(
            model_name='organisation',
            name='country_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
